
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hashika maduranga
 */
public class Match1Summery extends javax.swing.JFrame {

    /**
     * Creates new form Match1Summery
     */
    public Match1Summery() {
        initComponents();
         show_user("1");
    }
    public void close(){
        
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }

    
        public ArrayList<User>userList(String id){
        ArrayList<User>userList=new ArrayList<User>();
        
      //first match summery
        if(id.equals("1")){
        try{
             Class.forName("com.mysql.jdbc.Driver");
           
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/cricketdata","root","");
             
             String query1="SELECT * FROM  match_summery";
           
             
             java.sql.Statement st=con.createStatement();
             ResultSet rs1=st.executeQuery(query1);
             
              jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
             
           
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            }
        
        }
        else if(id.equals("2")){
            try{
             Class.forName("com.mysql.jdbc.Driver");
           
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/cricketdata","root","");
             
             String query1="SELECT * FROM  match2_summery";
           
             
             java.sql.Statement st=con.createStatement();
             ResultSet rs1=st.executeQuery(query1);
             
              jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
             
           /*  M1User user;
             while(rs1.next()){
                user=new M1User(rs1.getInt("id"),rs1.getInt("runs1"),rs1.getInt("runs2"),rs1.getInt("wicket1"),rs1.getInt("wicket2"),rs1.getString("name1"),rs1.getString("name2"),rs1.getString("name3"),rs1.getString("name4"));
                // user=new M1User(rs1.getInt("runs1"),rs1.getInt("runs2"),rs1.getInt("wicket1"),rs1.getInt("wicket2"),rs1.getString("name3"),rs1.getString("name4"));
                 userList.add(user);
             }*/
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            }
        }
         return userList;
        }
        
        
        public void show_user(String input){
         
       ArrayList<User> list=userList(input);
     
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
       /* Object[] row = new Object[8];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getName1();
            row[1]=list.get(i).getRuns1();
            row[2]=list.get(i).getName2();
            row[3]=list.get(i).getWicket1();
            row[4]=list.get(i).getName3();
            row[5]=list.get(i).getRuns2();
            row[6]=list.get(i).getName4();
            row[7]=list.get(i).getWicket2();
            
           
            
            
            model.addRow(row);
        }*/
    }
        
         public void selectedMatch(String getstring){
        
        if(getstring=="First_Inning"){
            
            userList(getstring);
            
            // cricket cr=new cricket();
             //cr.setVisible(true);
        }
        else if(getstring=="Second_Inning"){
             userList(getstring);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        IdMatch = new javax.swing.JTextField();
        Inningbtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Inning", "", "", "", "Second Inning", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Match Summery");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Micromax Cup");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        IdMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdMatchActionPerformed(evt);
            }
        });

        Inningbtn.setText("Innings");
        Inningbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InningbtnActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 0, 204));
        jButton4.setText("Sri Lanka Vs India");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(IdMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Inningbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 139, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(223, 223, 223)))))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(301, 301, 301))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(IdMatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inningbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id=IdMatch.getText();
        
        if(id.equals("1")){
                jButton4.setText("Sri Lanka Vs India");
                Inningbtn.setText("First Match Innings");
              /*  DefaultTableModel dm = (DefaultTableModel)jTable1.getModel();
                dm.getDataVector().removeAllElements();
                dm.fireTableDataChanged(); // notifies the JTable that the model has changed*/
                
                selectedMatch(id);
                show_user(id);
        }
        else if(id.equals("2")){
                jButton4.setText("Sri Lanka Vs Australia");
                Inningbtn.setText("Second Match Innings");
             /*  DefaultTableModel dm = (DefaultTableModel)jTable1.getModel();
                dm.getDataVector().removeAllElements();
                dm.fireTableDataChanged(); // notifies the JTable that the model has changed*/
                selectedMatch(id);
                show_user(id);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void InningbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InningbtnActionPerformed
     
        
        if(Inningbtn.getText()=="First Match Innings"){
            Main m=new Main();
            m.setVisible(true);
             close();
       }
       else if(Inningbtn.getText()=="Second Match Innings"){
           close();
           Main m=new Main();
            m.setVisible(true);
             
       }
       
    }//GEN-LAST:event_InningbtnActionPerformed

    private void IdMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdMatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdMatchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String id=IdMatch.getText();
        if(id.equals("1")){
            jButton4.setText("Sri Lanka Vs India");
        }
        else if(id.equals("2")){
            jButton4.setText("Sri Lanka Vs Australia");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
//        Match1Summery ms=new  Match1Summery();
//        ms.setVisible(true);
          
           
          
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Match1Summery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdMatch;
    private javax.swing.JButton Inningbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

   

   
}
